### ISSUE TITLE
What is the watcherID set to when there is an error?

### ISSUE THREAD

**Issue by msacchetti** [capacitor-community/background-geolocation#121]
`  let watcherId = await BackgroundGeolocation.addWatcher(...`

Two questions: 

1. If the plugin fails (throws an error in the callback) what is watcherId set to?

2. do we need try/catch blocks? or is the error always returned in the callback?

**Comment by diachedelic** [comment]
`addWatcher` can fail due to permission problems. If it fails, the watcher is never created and so there is no need for a watcher ID. You should handle the failure in case permissions are not granted.

**Comment by diachedelic** [comment]
Let's think about your example. Suppose the promise returned by `addWatcher` rejects. Execution of the `let` statement is aborted, and control is transferred to the nearest `catch` block in the call stack. Because there is no possible way for any code to access `watcherId`, its contents do not matter. Does that make sense?
