### ISSUE TITLE
Background location doesn't update on Android 11

### ISSUE THREAD

**Issue by nemoneph** [capacitor-community/background-geolocation#42]
**Describe the bug**
Hello,
First of all, thanks for all your work on this plugin.

I have a small app, with a background geolocation working fine until I switch to Android 11.
After further tests, it's always working on Android 8,9,10 but Android 11 it's doesn't update location when app is in Background.

It's seem link to this isssue / the need of ACCESS_BACKGROUND_LOCATION for Android 11 and above.
https://stackoverflow.com/questions/62483266/location-updates-in-android-11

https://developer.android.com/training/location/permissions

Does someone have any clue on this or trick ?

Thanks

**Comment by diachedelic** [comment]
Hi @nemoneph . According to Google's documentation, the `ACCESS_BACKGROUND_LOCATION` permission is only required where a location-gathering service is started in the background. This plugin technically only requests "foreground" updates:

> The system considers your app to be using foreground location if a feature of your app accesses the device's current location in one of the following situations:
> 1. An activity that belongs to your app is visible.
> 2. Your app is running a foreground service. When a foreground service is running, the system raises user awareness by showing a persistent notification. Your app retains access when it's placed in the background, such as when the user presses the Home button on their device or turns their device's display off.

Do you see the notification when your app is backgrounded on Android 11?

**Comment by nemoneph** [comment]
Yes, I see the notification bar when app is in Background.

And what I think (it's a assumption because I'm not an expert on this), it's that with Android 11, the technique with the foreground service which work fine on Android 9,10.. is not enough anymore.


Quote from stackoverflow "Starting with Android 11, a foreground "location" service is no longer enough to get background location updates. We now need to request ACCESS_BACKGROUND_LOCATION, if the foreground service is started in the background (such as a broadcast receiver):"

Maybe someone with Android 11 can confirm / invalid this theory ?

**Comment by diachedelic** [comment]
I think this is a key point from that StackOverflow post:

> if the foreground service is started in the background (such as a broadcast receiver)

In our case, the foreground service is started whilst the app is still in the foreground, so I still don't believe we should need the `ACCESS_BACKGROUND_LOCATION` permission. I will test this in the next few days on an Android 11 device and get back to you. In the meantime, I have a few questions:

1. What Android 11 device are you using?
2. Are you sure you are not being impacted by a "battery saving" feature? See [dontkillmyapp.com](https://dontkillmyapp.com/).
3. When you select the notification, does it open your app or does it open the settings app?

**Comment by nemoneph** [comment]
Yes I understand, you are probably right.

1. My Device is a Samsung Galaxy Note 10+.
My App was working when it's was on background on this device with Android 10.
After the update to Android 11, doesn't work anymore.

Note : some other apps in the same thematic (tracking running/cycling activity) like Strava work fine, but others made by small editors have the same problem on my device.

2. Hmm Samsung have bad review indeed .. Tested the dontkillmyapp app and I have a score of 64% (doesn't know what it's really mean).
Also, after that, I have excluded my app from battery optimizations. Doesn't change anything.

3. It open my app.

**Comment by diachedelic** [comment]
The plugin works on an Oppo Reno Z running Android 11. Unfortunately I do not have another Android 11 device to debug this issue on. Please let me know if you discover a solution.

**Comment by nemoneph** [comment]
OK, thanks for the feedback.
I close the issue, because it's seem links to my phone..

I will add a comment if I find the solution, or re-open if I find more info on my problem.

**Comment by NikolaStojicic** [comment]
After updating to Android 11, Xiaomi Poco F2 Pro doesnt update location in background (inspecting chrome dev tools, does not show result from native watcher), while Andorid 10, Huawei P30 Pro and Andorid 6 Nexus 5, works just fine.

**Comment by jamesdiacono** [comment]
Does the notification show when you send the app to the background, @NikolaStojicic ? If so, when you tap the notification, does it take you to the app or the settings?

**Comment by NikolaStojicic** [comment]
Notification is shown and when tapped it does take me to the settings.
It stoped working after latest phone update.
I switched to this plugin, which works fine for now (cuts off after 30min of phone being totally inactive, screen off, no movement)
https://github.com/seididieci/capacitor-backround-geolocation

**Comment by diachedelic** [comment]
When the notification takes you to the settings rather than the app, that generally means its icon has been misconfigured. Maybe this is causing the problem.

If anyone can discover why seididieci's plugin works but this one doesn't, I will implement a fix. The two plugins appear to use almost identical mechanisms.

**Comment by shipley-dcc** [comment]
I thought I should add my experience here in case it helps anyone. I had a similar experience with some users expressing issues with my app tracking location in the background on Android 11. But I tested it on BrowserStack with a Samsung Galaxy S21 and a Google Pixel 5 and the app worked fine on both devices with Android 11. However, I got hold of a Nokia 1.4 with Android Go Edition version 11 and the app did stop tracking in the background. The fix for this was to add the ACCESS_BACKGROUND_LOCATION permission to my app. I now request the usual COARSE and FINE permissions and then if the app is running on an Android device with an OS version greater than 10 I then ask for the BACKGROUND permission which opens the Settings app and the user has to set it manually. This contradicts the Android Developer documentation, but there you go.

**Comment by diachedelic** [comment]
Thanks Dave. Weirdly, the fix for seididieci's plugin actually [removes that permission](https://github.com/seididieci/capacitor-backround-geolocation/commit/20e2467b599fe810acc64f610238797bc9904a71)! So I am still a bit confused. @NikolaStojicic , do you request the ACCESS_BACKGROUND_LOCATION permission in AndroidManifest.xml?

**Comment by shipley-dcc** [comment]
You can't ask for all three permissions at once, you have to ask for foreground permission (COARSE and/or FINE), then ask for BACKGROUND permission in a separate request. So maybe Seididieci's plugin was running into that issue.

**Comment by NikolaStojicic** [comment]
@diachedelic I did request ACCESS_BACKGROUND_LOCATION.
The app I m creating won't be published on Play Store, so I didn't test if it would make difference without it.

**Comment by diachedelic** [comment]
I suspect that declaring the permission in the manifest is different from requesting it at runtime.

> However, I got hold of a Nokia 1.4 with Android Go Edition version 11 and the app did stop tracking in the background.

It occurs to me that the OS might be preventing your app from running in the background. Have you investigated https://dontkillmyapp.com?

**Comment by ahmadmasoum** [comment]
I have the same issue on Samsung a51 android 11 background location works for few minutes (2 - 5) then stops until you open the app again 

Side note: I'm also using [Background Mode plugin](https://ionicframework.com/docs/native/background-mode)  in order to receive signalR updates from the server and it works even after 30mins (Both plugins are used on the same app and the same phone).

**Comment by diachedelic** [comment]
@ahmadmasoum Do you see the notification when the app is moved to the background? What happens when you tap the notification - does it open the app or the settings?

**Comment by ahmadmasoum** [comment]
> @ahmadmasoum Do you see the notification when the app is moved to the background? What happens when you tap the notification - does it open the app or the settings?

Yes, it opens the settings page

**Comment by diachedelic** [comment]
@ahmadmasoum In my experience, that means the notification icon has been misconfigured. Perhaps it is also affecting the emission of location updates. If you have configured an icon in AndroidManifest.xml, can you remove it and see if that a) fixes the notification tap behaviour, and b) fixes your background locations?

**Comment by ahmadmasoum** [comment]
It turns out it wasn't notification configuration problem 
Even though i disabled optimization from settings  i had to call 
```typescript
        this.backgroundMode.disableBatteryOptimizations();
        this.backgroundMode.disableWebViewOptimizations()
```

when background mode is active.
List this 

```typescript
      this.activateSubscription = this.backgroundMode.on('activate').subscribe(() => {
        this.backgroundMode.disableBatteryOptimizations();
        this.backgroundMode.disableWebViewOptimizations();
      });
```
[This is the background mode plugin im using](https://github.com/katzer/cordova-plugin-background-mode)

Note: the `disableBatteryOptimizations();` and `disableWebViewOptimizations()` must be called when the background mode is active otherwise the app will stop after 5 minutes

**Comment by diachedelic** [comment]
@ahmadmsoum Thanks for the valuable workaround. For those interested in how those two methods work, [here are their implementations](https://github.com/katzer/cordova-plugin-background-mode/blob/0a6bf35cb9f2bfcb8a0a79767b57158e17a32f13/src/android/BackgroundModeExt.java#L163). It appears that Android supports a [REQUEST_IGNORE_BATTERY_OPTIMIZATIONS](https://developer.android.com/reference/android/Manifest.permission#REQUEST_IGNORE_BATTERY_OPTIMIZATIONS) permission.
